# Site settings
title: PHP7开发体验
email: sunshine17.lin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  为PHP7开发体验而开的博客
baseurl: "/php7-exp/" # the subpath of your site, e.g. /blog/
url: "http://sunshine17.github.io" # the base hostname & protocol for your site
twitter_username: sunshine17.lin@gmail.com
github_username:  sunshine17.lin@gmail.com

# Build settings
markdown: kramdown
